### ISSUE TITLE
undefined: url.PathEscape

### ISSUE THREAD

**Issue by IAD** [zemirco/couchdb#11]
$ go get -u github.com/zemirco/couchdb
# github.com/zemirco/couchdb
../../../github.com/zemirco/couchdb/client.go:92: undefined: url.PathEscape
../../../github.com/zemirco/couchdb/client.go:104: undefined: url.PathEscape
../../../github.com/zemirco/couchdb/client.go:116: undefined: url.PathEscape
../../../github.com/zemirco/couchdb/database.go:75: undefined: url.PathEscape
../../../github.com/zemirco/couchdb/database.go:87: undefined: url.PathEscape
../../../github.com/zemirco/couchdb/database.go:97: undefined: url.PathEscape
../../../github.com/zemirco/couchdb/database.go:108: undefined: url.PathEscape
../../../github.com/zemirco/couchdb/database.go:128: undefined: url.PathEscape
../../../github.com/zemirco/couchdb/database.go:139: undefined: url.PathEscape
../../../github.com/zemirco/couchdb/database.go:153: undefined: url.PathEscape
../../../github.com/zemirco/couchdb/database.go:153: too many errors

**Comment by zemirco** [comment]
Which go version are you using? `url.PathEscape` is available from 1.8 https://golang.org/doc/go1.8#net_url

**Comment by IAD** [comment]
Hello @zemirco 
go version go1.7.5 linux/amd64

**Comment by zemirco** [comment]
If you upgrade to 1.8 the issue should be gone.

**Comment by IAD** [comment]
@zemirco ty for the fast feedback!
