### ISSUE TITLE
Is there a way to purge?

### ISSUE THREAD

**Issue by enst** [zemirco/couchdb#3]
https://wiki.apache.org/couchdb/Purge_Documents

Thanks,

**Comment by zemirco** [comment]
Not yet. We are currently moving into our new apartment and I won't have time the next 2-3 weeks. Then I'll add purge.

**Comment by zemirco** [comment]
see https://github.com/zemirco/couchdb/commit/2da4eb7b17acbbce200c6cfcadef75518823fc36
