### ISSUE TITLE
Slashes in DB Names and DocIDs should be escaped

### ISSUE THREAD

**Issue by ryanjyoder** [zemirco/couchdb#8]
When using slashes in a database name (or doc_id), the slash needs to be escaped as %2F in the URL. Other special characters may also need to escaped?

I used url.PathEscape to do this, which seems to work...
https://github.com/zemirco/couchdb/compare/master...ryanjyoder:handle_slashes_in_names

**Comment by zemirco** [comment]
sounds right. could you add a test and create a pull request?

**Comment by zemirco** [comment]
done in https://github.com/zemirco/couchdb/pull/9. thank you!
